window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('t228_overflow',!0,!0);noOverflowEvent.initEvent('t228_nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('t228_overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('t228_nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile&&window.innerWidth<=980){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}
t_onFuncLoad('t_throttle',function(){var onResizeThrottled=t_throttle(function(){t228_setWidth(recid)},50);window.addEventListener('resize',onResizeThrottled)})}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',windowHeight-mobileContainerHeight+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});leftSide.style.minWidth='';rightSide.style.minWidth='';if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}
if(menuList&&menuList.classList.contains('t228__list_hidden'))
menuList.classList.remove('t228__list_hidden')})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t635_init(recid,textColor,cursorColor){var rec=document.getElementById('rec'+recid);if(!rec)return;var textHolder=rec.querySelector('.t635__textholder');if(!textHolder)return;var typingRecIdList=textHolder.getAttribute('data-recid').split(',');if(typingRecIdList.length===0)return;t635_processCursorAndTextColor(rec,typingRecIdList,textColor,cursorColor);typingRecIdList.forEach(function(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return;var screenMin=parseInt(animBlock.getAttribute('data-screen-min'),10);var screenMax=parseInt(animBlock.getAttribute('data-screen-max'),10);if(isNaN(screenMax)&&isNaN(screenMin)){t635_startType(animRecId,textHolder)}else if(!isNaN(screenMax)&&!isNaN(screenMin)){if(window.innerWidth>=screenMin&&window.innerWidth<=screenMax){t635_startType(animRecId,textHolder)}}else if(!isNaN(screenMax)){if(window.innerWidth<=screenMax){t635_startType(animRecId,textHolder)}}else if(!isNaN(screenMin)){if(window.innerWidth>=screenMin){t635_startType(animRecId,textHolder)}}})}
function t635_processCursorAndTextColor(rec,typingRecIdList,textColor,cursorColor){if(!textColor&&!cursorColor)return;var style=document.createElement('style');var styleContent='';typingRecIdList.forEach(function(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return;if(textColor)styleContent+='#rec'+animRecId+' .t635__typing-text{color: '+textColor+';}';if(cursorColor)styleContent+='#rec'+animRecId+' .typed-cursor{color: '+cursorColor+';}'});if(!styleContent)return;style.textContent=styleContent;rec.appendChild(style)}
function t635_startType(animRecId,textHolder){var animTextElems=t635_findAnimElems(animRecId);if(!animTextElems.length)return;animTextElems.forEach(function(elem){t635_wrapTypingTextSpan(elem)});setTimeout(function(){t635_updateAnimTextLimits(animRecId);t635_updateAnimTextLimitsOnResize(animRecId);t_onFuncLoad('Typed',function(){t635_updateTypingOnFuncLoad(animRecId,textHolder)})})}
function t635_updateTypingOnFuncLoad(animRecId,textHolder){var phrasesList=[];for(var i=0;i<=5;i+=1){var currentPhrase=textHolder.getAttribute('data-text'+i);if(typeof currentPhrase==='string')phrasesList.push(currentPhrase.slice(0,80))}
if(!phrasesList.length)return;var animSpeed=parseInt(textHolder.getAttribute('data-speed'),10);var backspaceDelay=parseInt(textHolder.getAttribute('data-backspacing-delay'),10);var isTypingLoopDisabled=textHolder.getAttribute('data-loop')==='false';var animBlock=document.getElementById('rec'+animRecId);var animatedTextElems=animBlock.querySelectorAll('.t635__typing-text');if(!animatedTextElems.length)return;var isZeroBlock=!!animBlock.querySelector('.t396');animatedTextElems.forEach(function(animatedText){var currentStateObj=t635_getCurrentScrollStateObj(animatedText);var zeroElem=animatedText.closest('.t396__elem');var isSBSAnimation=zeroElem&&zeroElem.getAttribute('data-animate-sbs-event');var typedInstance=t635_animateText(animatedText,phrasesList,animSpeed,isTypingLoopDisabled,backspaceDelay);if(currentStateObj.animTextBottom<currentStateObj.windowTop||currentStateObj.animTextTop>currentStateObj.windowBottom){t635_updatetypedInstance(typedInstance,'stop',!0)}
if('IntersectionObserver' in window&&!isSBSAnimation){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){t635_processObservedTyping(entry,isTypingLoopDisabled,typedInstance)})});t635_processIntersectionObserver(function(){observer.observe(animatedText)})}else{var timerID=0;window.addEventListener('scroll',function(){if(timerID)return;timerID=setTimeout(function(){var currentStateObj=t635_getCurrentScrollStateObj(animatedText);var isOutside=currentStateObj.animTextBottom<currentStateObj.windowTop;if(!isOutside)isOutside=currentStateObj.animTextTop>currentStateObj.windowBottom;if(!isTypingLoopDisabled&&isOutside){t635_updatetypedInstance(typedInstance,'stop',!0)}else{t635_updatetypedInstance(typedInstance,'start',!1)}
clearTimeout(timerID);timerID=0},700)})}});if(isZeroBlock){var event=document.createEvent('HTMLEvents');event.initEvent('animationInited',!0,!1);window.dispatchEvent(event)}}
function t635_updatetypedInstance(typedInstance,action,resetFlag){if(resetFlag&&action==='stop')typedInstance.reset();typedInstance[action]()}
function t635_getCurrentScrollStateObj(animatedText){var animTextTop=animatedText.getAttribute('data-top-limit');var animTextBottom=animatedText.getAttribute('data-bottom-limit');var windowTop=window.pageYOffset;var windowBottom=windowTop+window.innerHeight;return{animTextTop:animTextTop,animTextBottom:animTextBottom,windowTop:windowTop,windowBottom:windowBottom,}}
function t635_processIntersectionObserver(callback){var recT809=document.querySelector('[data-record-type="809"], [data-parenttplid="809"]');if(!recT809){callback()}else{if(recT809.getAttribute('data-replacement-completed')==='yes'){callback()}else{document.addEventListener('replacingCompletedT809',function(){callback()})}}}
function t635_processObservedTyping(entry,isTypingLoopDisabled,typedInstance){if(!entry.isIntersecting&&isTypingLoopDisabled)return;if(entry.isIntersecting){var isTypeInited=Boolean(entry.target.typeInited);if(isTypeInited){t635_updatetypedInstance(typedInstance,'start',!1)}else{setTimeout(function(){t635_updatetypedInstance(typedInstance,'start',!1);entry.target.typeInited=!0},1000)}}else if(!isTypingLoopDisabled){t635_updatetypedInstance(typedInstance,'stop',!1)}}
function t635_findElementsWithAnimation(root){var result=[];var walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){if(node.textContent.includes('|')){return NodeFilter.FILTER_ACCEPT}
return NodeFilter.FILTER_REJECT},});while(walker.nextNode()){var node=walker.currentNode;if(!['SCRIPT','STYLE'].includes(node.parentElement.tagName)){result.push(node.parentElement)}}
return Array.from(new Set(result))}
function t635_wrapTypingTextSpan(animText){var animTextHtml=animText.innerHTML;var animTextSplitted=animTextHtml.split('|');animText.innerHTML=animTextSplitted[0]+'<span class="t635__typing-text"></span>'+animTextSplitted[1]}
function t635_findAnimElems(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return[];var elementsWithAnimation=t635_findElementsWithAnimation(animBlock);return elementsWithAnimation}
function t635_updateAnimTextLimits(animRecId){var animBlock=document.getElementById('rec'+animRecId);var animTextElems=animBlock?animBlock.querySelectorAll('.t635__typing-text'):[];if(!animTextElems.length)return;animTextElems.forEach(function(elem){var topLimit=elem.getBoundingClientRect().top+window.pageYOffset;var bottomLimit=elem.getBoundingClientRect().top+window.pageYOffset+animBlock.clientHeight;elem.setAttribute('data-top-limit',topLimit.toString());elem.setAttribute('data-bottom-limit',bottomLimit.toString())})}
function t635_updateAnimTextLimitsOnResize(animRecId){var timerID=0;var isTouchDevice=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);if(!isTouchDevice)isTouchDevice='ontouchend' in document&&navigator.userAgent.indexOf('AppleWebKit')!==-1;window.addEventListener(isTouchDevice?'orientationchange':'resize',function(){if(timerID)return;timerID=setTimeout(function(){t635_updateAnimTextLimits(animRecId);clearTimeout(timerID);timerID=0},600)})}
function t635_animateText(element,phrasesList,animSpeed,isTypingLoopDisabled,backspaceDelay){if(!animSpeed||animSpeed<0)animSpeed=40;if(!backspaceDelay||backspaceDelay<0)backspaceDelay=800;return new Typed(element,{strings:phrasesList,typeSpeed:animSpeed,startDelay:600,backDelay:backspaceDelay,loop:!isTypingLoopDisabled,})}
var t778_POPUP_SHOWED_EVENT_NAME='catalog:popupShowed';var t778_POPUP_CLOSED_EVENT_NAME='catalog:popupClosed';function t778__init(recid){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t778_initPopup(recid);t778__hoverZoom_init(recid);t778__updateLazyLoad(recid);t778_initQuantityInputs(recid);var rec=document.getElementById('rec'+recid);if(!rec)return;var quantityBtns=rec.querySelectorAll('.t778__col .t-store__prod__quantity, .t778__product-full .t-store__prod__quantity');if(quantityBtns.length){t_onFuncLoad('t_store_addProductQuantityEvents',function(){t778_initProductQuantity(recid)})}
var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)}
function t778_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t778__col, .t778__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t778__showMore(recid){var rec=document.querySelector('#rec'+recid+' .t778');if(!rec)return;var cardsShowLimit=parseInt(rec.getAttribute('data-show-count'),10);if(isNaN(cardsShowLimit)||cardsShowLimit<=0)return;var showMoreButton=rec.querySelector('.t778__showmore');if(!showMoreButton)return;const showMoreTextContainer=showMoreButton.querySelector('.js-btn-txt');if(showMoreTextContainer){showMoreTextContainer.textContent=t778__dict()}
showMoreButton.style.removeProperty('display');var allProductCards=rec.querySelectorAll('.t778__col');Array.prototype.forEach.call(allProductCards,function(productCard){productCard.style.display='none'});var cardsNumber=allProductCards.length;t778__showSeparator(rec,cardsShowLimit);for(var i=0;i<cardsShowLimit;i++){if(allProductCards[i]){allProductCards[i].style.display='inline-block'}}
showMoreButton.addEventListener('click',function(){var currentColumns=rec.querySelectorAll('.t778__col');var currentColumnsShowed=0;Array.prototype.forEach.call(currentColumns,function(column){if(column.style.display==='inline-block'){++currentColumnsShowed}});for(var i=0;i<cardsShowLimit+currentColumnsShowed;i++){if(allProductCards[i]){allProductCards[i].style.display='inline-block'}}
var event=document.createEvent('HTMLEvents');event.initEvent('displayChanged',!0,!1);rec.dispatchEvent(event);if(cardsShowLimit+currentColumnsShowed>=cardsNumber){showMoreButton.style.display='none'}
t778__showSeparator(rec,cardsShowLimit+currentColumnsShowed);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t778__showSeparator(rec,cardsShowLimit){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t778__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t778__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsShowLimit){separator.classList.remove('t778__separator_hide')}})}
function t778__dict(){var dictionary={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t778__hoverZoom_init(recid){if(window.isMobile)return;var rec=document.getElementById('rec'+recid);if(!rec)return;try{if(!rec.querySelector('[data-hover-zoom]')){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t778__updateLazyLoad(recid){var scrollContainer=document.querySelector('#rec'+recid+' .t778__container_mobile-flex');var tRecords=document.querySelector('.t-records');if(!tRecords)return;var currentMode=tRecords.getAttribute('data-tilda-mode');var colFixed=document.querySelector('#rec'+recid+' .t778__col_fixed');var allRecords=document.getElementById('allrecords');var scrollFunc=t_throttle(function(){if(window.lazy==='y'||(allRecords&&allRecords.getAttribute('data-tilda-lazy')==='yes')){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});if(currentMode!=='edit'&&currentMode!=='preview'){if(scrollContainer)scrollContainer.addEventListener('scroll',scrollFunc);if(colFixed){var popup=document.querySelector('#rec'+recid+' .t-popup');if(popup)popup.addEventListener('scroll',scrollFunc)}}}
function t778_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allPopupLinks=rec.querySelectorAll('[href^="#prodpopup"]');if(!allPopupLinks.length)return;var popup=rec.querySelector('.t-popup');popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t778_closePopup(document.body,popup)}});Array.prototype.forEach.call(allPopupLinks,function(popupLink){var product=popupLink.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productLinks=document.querySelectorAll('.r a[href$="#!/tproduct/'+recid+'-'+productLid+'"]');Array.prototype.forEach.call(productLinks,function(productLink){productLink.addEventListener('click',function(){if(rec.querySelector('[data-product-lid="'+productLid+'"]')){var linkToPopup=product.querySelector('[href^="#prodpopup"]');if(linkToPopup){var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);linkToPopup.dispatchEvent(event)}}})});popupLink.addEventListener('click',clickOnceHandler,{once:!0});function clickOnceHandler(event){event.preventDefault();t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t778__product-'+productLid)});popupLink.removeEventListener('click',clickOnceHandler,!1)}
popupLink.addEventListener('click',function(event){event.preventDefault();if(event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn')){return}
t778_showPopup(recid);Array.prototype.forEach.call(popup.querySelectorAll('.js-product'),function(product){product.style.display='none'});var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');if(productFull){productFull.style.display='block'}
var analitics=popup.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtualTitle=productName.textContent;if(!virtualTitle){virtualTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtualTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')===-1&&currentUrl.indexOf('%23!/tproduct/')===-1){if(history.replaceState){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t778_updateSlider(recid+' #t778__product-'+productLid);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500)})});if(!document.getElementById('record'+recid)){t778_checkUrl(recid)}
if(popup&&popup.hasAttribute('data-fixed-button')){t778_fixedPopupButton(recid)}}
function t778_checkUrl(recid){if(window.catalogUrlProcessed)return;var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}
if(typeof rec.scrollIntoView==='function'){rec.scrollIntoView({block:'start'})}
window.catalogUrlProcessed=!0}}}
function t778_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft,10)||0;var paddingRight=parseInt(slider.style.paddingRight,10)||0;var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var position=parseInt(sliderWrapper.getAttribute('data-slider-pos'),10);sliderWrapper.style.transform='translate3d(-'+sliderWidth*position+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t778_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t_triggerEvent(popup,t778_POPUP_SHOWED_EVENT_NAME)},50);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},300);if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event);var closeButtons=document.querySelectorAll('.t-popup__close, .t778__close-text');Array.prototype.forEach.call(closeButtons,function(closeButton){closeButton.addEventListener('click',function(){t778_closePopup(document.body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.key==='Escape'){t778_closePopup(document.body,popup)}}})}
function t778_closePopup(body,popup){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove!==-1){indexToRemove=currentUrl.indexOf('%23!/tproduct/')}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';if(history.replaceState){window.history.replaceState('','',currentUrl)}},300);t_triggerEvent(popup,t778_POPUP_CLOSED_EVENT_NAME)}
function t778_fixedPopupButton(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var MOBILE_MAX_WIDTH=560;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var btnWrappers=rec.querySelectorAll('.t778__btn-wrapper');Array.prototype.forEach.call(btnWrappers,function(el){el.classList.add('t778__btn-wrapper-fixed')});function addStyle(){popupContainer.style.paddingBottom='90px';popupContainer.style.cssText+=';transform:none !important;'}
function resetStyle(){popupContainer.style.paddingBottom='';popupContainer.style.transform=''}
function handleResize(){if(window.innerWidth>MOBILE_MAX_WIDTH){resetStyle();return}
addStyle()}
if(window.isMobile){window.addEventListener('orientationchange',handleResize)}
popup.addEventListener(t778_POPUP_SHOWED_EVENT_NAME,function(){setTimeout(function(){handleResize()})});popup.addEventListener(t778_POPUP_CLOSED_EVENT_NAME,function(){resetStyle()});window.addEventListener('resize',handleResize)}
function t778_initQuantityInputs(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var quantityInputs=rec.querySelectorAll('.t-store__prod__quantity-input');Array.prototype.forEach.call(quantityInputs,function(input){var maxValue=parseInt(input.getAttribute('max'),10);var minValue=parseInt(input.getAttribute('min'),10);input.addEventListener('input',function(e){var value=parseInt(e.target.value,10);if(value>maxValue){input.value=99999;return}
if(value<minValue){input.value=1}})})}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var undercuts=rec.querySelectorAll('.ql-undercut');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t585__trigger-button');var activeHeight=0;var isAccordionDown=!1;if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded}
if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';var zoom=1;if(rec&&rec.classList.contains('t-record_scaled')){zoom=parseFloat(getComputedStyle(rec).zoom)||1}
setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){activeHeight*=zoom;t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
for(var i=0;i<undercuts.length;i++){undercuts[i].addEventListener('click',function(event){const target=event.target;const content=target.closest('.t585__content');const textBlock=target.closest('.t585__textwrapper');setTimeout(()=>{content.style.maxHeight=textBlock.scrollHeight+'px'},0)})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader){var activeContainer=activeHeader.nextElementSibling}
if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return(change/2)*currentTime*currentTime*currentTime+start}else{return(change/2)*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}