window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('t228_overflow',!0,!0);noOverflowEvent.initEvent('t228_nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('t228_overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('t228_nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile&&window.innerWidth<=980){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}
t_onFuncLoad('t_throttle',function(){var onResizeThrottled=t_throttle(function(){t228_setWidth(recid)},50);window.addEventListener('resize',onResizeThrottled)})}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',windowHeight-mobileContainerHeight+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});leftSide.style.minWidth='';rightSide.style.minWidth='';if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}
if(menuList&&menuList.classList.contains('t228__list_hidden'))
menuList.classList.remove('t228__list_hidden')})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t635_init(recid,textColor,cursorColor){var rec=document.getElementById('rec'+recid);if(!rec)return;var textHolder=rec.querySelector('.t635__textholder');if(!textHolder)return;var typingRecIdList=textHolder.getAttribute('data-recid').split(',');if(typingRecIdList.length===0)return;t635_processCursorAndTextColor(rec,typingRecIdList,textColor,cursorColor);typingRecIdList.forEach(function(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return;var screenMin=parseInt(animBlock.getAttribute('data-screen-min'),10);var screenMax=parseInt(animBlock.getAttribute('data-screen-max'),10);if(isNaN(screenMax)&&isNaN(screenMin)){t635_startType(animRecId,textHolder)}else if(!isNaN(screenMax)&&!isNaN(screenMin)){if(window.innerWidth>=screenMin&&window.innerWidth<=screenMax){t635_startType(animRecId,textHolder)}}else if(!isNaN(screenMax)){if(window.innerWidth<=screenMax){t635_startType(animRecId,textHolder)}}else if(!isNaN(screenMin)){if(window.innerWidth>=screenMin){t635_startType(animRecId,textHolder)}}})}
function t635_processCursorAndTextColor(rec,typingRecIdList,textColor,cursorColor){if(!textColor&&!cursorColor)return;var style=document.createElement('style');var styleContent='';typingRecIdList.forEach(function(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return;if(textColor)styleContent+='#rec'+animRecId+' .t635__typing-text{color: '+textColor+';}';if(cursorColor)styleContent+='#rec'+animRecId+' .typed-cursor{color: '+cursorColor+';}'});if(!styleContent)return;style.textContent=styleContent;rec.appendChild(style)}
function t635_startType(animRecId,textHolder){var animTextElems=t635_findAnimElems(animRecId);if(!animTextElems.length)return;animTextElems.forEach(function(elem){t635_wrapTypingTextSpan(elem)});setTimeout(function(){t635_updateAnimTextLimits(animRecId);t635_updateAnimTextLimitsOnResize(animRecId);t_onFuncLoad('Typed',function(){t635_updateTypingOnFuncLoad(animRecId,textHolder)})})}
function t635_updateTypingOnFuncLoad(animRecId,textHolder){var phrasesList=[];for(var i=0;i<=5;i+=1){var currentPhrase=textHolder.getAttribute('data-text'+i);if(typeof currentPhrase==='string')phrasesList.push(currentPhrase.slice(0,80))}
if(!phrasesList.length)return;var animSpeed=parseInt(textHolder.getAttribute('data-speed'),10);var backspaceDelay=parseInt(textHolder.getAttribute('data-backspacing-delay'),10);var isTypingLoopDisabled=textHolder.getAttribute('data-loop')==='false';var animBlock=document.getElementById('rec'+animRecId);var animatedTextElems=animBlock.querySelectorAll('.t635__typing-text');if(!animatedTextElems.length)return;var isZeroBlock=!!animBlock.querySelector('.t396');animatedTextElems.forEach(function(animatedText){var currentStateObj=t635_getCurrentScrollStateObj(animatedText);var zeroElem=animatedText.closest('.t396__elem');var isSBSAnimation=zeroElem&&zeroElem.getAttribute('data-animate-sbs-event');var typedInstance=t635_animateText(animatedText,phrasesList,animSpeed,isTypingLoopDisabled,backspaceDelay);if(currentStateObj.animTextBottom<currentStateObj.windowTop||currentStateObj.animTextTop>currentStateObj.windowBottom){t635_updatetypedInstance(typedInstance,'stop',!0)}
if('IntersectionObserver' in window&&!isSBSAnimation){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){t635_processObservedTyping(entry,isTypingLoopDisabled,typedInstance)})});t635_processIntersectionObserver(function(){observer.observe(animatedText)})}else{var timerID=0;window.addEventListener('scroll',function(){if(timerID)return;timerID=setTimeout(function(){var currentStateObj=t635_getCurrentScrollStateObj(animatedText);var isOutside=currentStateObj.animTextBottom<currentStateObj.windowTop;if(!isOutside)isOutside=currentStateObj.animTextTop>currentStateObj.windowBottom;if(!isTypingLoopDisabled&&isOutside){t635_updatetypedInstance(typedInstance,'stop',!0)}else{t635_updatetypedInstance(typedInstance,'start',!1)}
clearTimeout(timerID);timerID=0},700)})}});if(isZeroBlock){var event=document.createEvent('HTMLEvents');event.initEvent('animationInited',!0,!1);window.dispatchEvent(event)}}
function t635_updatetypedInstance(typedInstance,action,resetFlag){if(resetFlag&&action==='stop')typedInstance.reset();typedInstance[action]()}
function t635_getCurrentScrollStateObj(animatedText){var animTextTop=animatedText.getAttribute('data-top-limit');var animTextBottom=animatedText.getAttribute('data-bottom-limit');var windowTop=window.pageYOffset;var windowBottom=windowTop+window.innerHeight;return{animTextTop:animTextTop,animTextBottom:animTextBottom,windowTop:windowTop,windowBottom:windowBottom,}}
function t635_processIntersectionObserver(callback){var recT809=document.querySelector('[data-record-type="809"], [data-parenttplid="809"]');if(!recT809){callback()}else{if(recT809.getAttribute('data-replacement-completed')==='yes'){callback()}else{document.addEventListener('replacingCompletedT809',function(){callback()})}}}
function t635_processObservedTyping(entry,isTypingLoopDisabled,typedInstance){if(!entry.isIntersecting&&isTypingLoopDisabled)return;if(entry.isIntersecting){var isTypeInited=Boolean(entry.target.typeInited);if(isTypeInited){t635_updatetypedInstance(typedInstance,'start',!1)}else{setTimeout(function(){t635_updatetypedInstance(typedInstance,'start',!1);entry.target.typeInited=!0},1000)}}else if(!isTypingLoopDisabled){t635_updatetypedInstance(typedInstance,'stop',!1)}}
function t635_findElementsWithAnimation(root){var result=[];var walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){if(node.textContent.includes('|')){return NodeFilter.FILTER_ACCEPT}
return NodeFilter.FILTER_REJECT},});while(walker.nextNode()){var node=walker.currentNode;if(!['SCRIPT','STYLE'].includes(node.parentElement.tagName)){result.push(node.parentElement)}}
return Array.from(new Set(result))}
function t635_wrapTypingTextSpan(animText){var animTextHtml=animText.innerHTML;var animTextSplitted=animTextHtml.split('|');animText.innerHTML=animTextSplitted[0]+'<span class="t635__typing-text"></span>'+animTextSplitted[1]}
function t635_findAnimElems(animRecId){var animBlock=document.getElementById('rec'+animRecId);if(!animBlock)return[];var elementsWithAnimation=t635_findElementsWithAnimation(animBlock);return elementsWithAnimation}
function t635_updateAnimTextLimits(animRecId){var animBlock=document.getElementById('rec'+animRecId);var animTextElems=animBlock?animBlock.querySelectorAll('.t635__typing-text'):[];if(!animTextElems.length)return;animTextElems.forEach(function(elem){var topLimit=elem.getBoundingClientRect().top+window.pageYOffset;var bottomLimit=elem.getBoundingClientRect().top+window.pageYOffset+animBlock.clientHeight;elem.setAttribute('data-top-limit',topLimit.toString());elem.setAttribute('data-bottom-limit',bottomLimit.toString())})}
function t635_updateAnimTextLimitsOnResize(animRecId){var timerID=0;var isTouchDevice=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);if(!isTouchDevice)isTouchDevice='ontouchend' in document&&navigator.userAgent.indexOf('AppleWebKit')!==-1;window.addEventListener(isTouchDevice?'orientationchange':'resize',function(){if(timerID)return;timerID=setTimeout(function(){t635_updateAnimTextLimits(animRecId);clearTimeout(timerID);timerID=0},600)})}
function t635_animateText(element,phrasesList,animSpeed,isTypingLoopDisabled,backspaceDelay){if(!animSpeed||animSpeed<0)animSpeed=40;if(!backspaceDelay||backspaceDelay<0)backspaceDelay=800;return new Typed(element,{strings:phrasesList,typeSpeed:animSpeed,startDelay:600,backDelay:backspaceDelay,loop:!isTypingLoopDisabled,})}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var undercuts=rec.querySelectorAll('.ql-undercut');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t585__trigger-button');var activeHeight=0;var isAccordionDown=!1;if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded}
if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';var zoom=1;if(rec&&rec.classList.contains('t-record_scaled')){zoom=parseFloat(getComputedStyle(rec).zoom)||1}
setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){activeHeight*=zoom;t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
for(var i=0;i<undercuts.length;i++){undercuts[i].addEventListener('click',function(event){const target=event.target;const content=target.closest('.t585__content');const textBlock=target.closest('.t585__textwrapper');setTimeout(()=>{content.style.maxHeight=textBlock.scrollHeight+'px'},0)})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader){var activeContainer=activeHeader.nextElementSibling}
if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return(change/2)*currentTime*currentTime*currentTime+start}else{return(change/2)*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t718_onSuccess(form){form=form[0]?form[0]:form;if(!form)return;if(form.tagName&&form.tagName.toLowerCase()==='input'){form=form.closest('.t-form')}
var inputsWrapper=form.querySelector('.t-form__inputsbox');if(!inputsWrapper)return;var paddingTopInputs=parseInt(inputsWrapper.style.paddingTop,10)||0;var paddingBottomInputs=parseInt(inputsWrapper.style.paddingBottom,10)||0;var inputsHeight=inputsWrapper.clientHeight-(paddingTopInputs+paddingBottomInputs);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var targetOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=null;if(window.innerWidth>960){target=targetOffset-200}else{target=targetOffset-100}
var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(targetOffset>window.pageYOffset||documentHeight-inputsBottom<window.innerHeight-100){var body=document.body;var paddingTopBody=parseInt(body.style.paddingTop,10)||0;var paddingBottomBody=parseInt(body.style.paddingBottom,10)||0;var bodyHeight=body.clientHeight-(paddingTopBody+paddingBottomBody);setTimeout(function(){if(window.innerHeight>bodyHeight){setTimeout(function(){var tildaLabel=document.querySelector('.t-tildalabel');if(!tildaLabel)return;t718__fadeOut(tildaLabel)},50)}},300)}else{t718_scrollToTop(target)}
var successUrl=form.getAttribute('data-success-url');if(successUrl){t_forms__handleRedirect(form,successUrl,successBox)}}
function t718_scrollToTop(target){if(target===window.pageYOffset){return!1}
var duration=400;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(Math.abs(window.pageYOffset-target)*10)/duration;var scrollInterval=setInterval(function(){if(cashedDiff>target){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>target&&window.pageYOffset<=target){document.body.removeAttribute('data-scrollable');clearInterval(scrollInterval)}else if(cashedDiff<=target&&window.pageYOffset>=target){document.body.removeAttribute('data-scrollable');window.scrollTo(0,target);clearInterval(scrollInterval)}},10);var scrollTimeout=setTimeout(function(){clearInterval(scrollInterval);document.body.removeAttribute('data-scrollable');clearTimeout(scrollTimeout)},duration*2)}
function t718__fadeOut(element){if(element.style.display==='none')return;var opacity=1;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);element.style.display='none';element.style.opacity=null}},50)}